# Generated by Django 3.1.7 on 2021-03-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('apply', models.CharField(max_length=1000)),
                ('tag', models.CharField(choices=[('1', 'Programming'), ('2', 'Science'), ('3', 'Sales'), ('4', 'Technical')], default='1', max_length=2)),
                ('job_summary', models.TextField(default='Enter job description.')),
                ('minimum_requirements', models.TextField(default='Enter minimum requirements.')),
                ('preferred_requirements', models.TextField(blank=True, default='Enter minimum requirements.', null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=30, null=True)),
                ('days_posted', models.DateField(default='03/18/2021')),
                ('company_logo', models.ImageField(default='/company_logos/default.png', upload_to='company_logos')),
            ],
            options={
                'ordering': ['-days_posted'],
                'permissions': [('employer', 'Can post new jobs')],
            },
        ),
    ]
