# Generated by Django 3.1.7 on 2021-03-20 00:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_jobs', '0002_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='days_posted',
            field=models.DateField(default='03/19/2021'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_summary',
            field=ckeditor.fields.RichTextField(default='Enter job description.'),
        ),
    ]
