# Generated by Django 3.1.7 on 2021-03-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_jobs', '0004_auto_20210319_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='images/company_logos/default.png', upload_to='company_logos'),
        ),
    ]
