# Generated by Django 3.2.8 on 2021-10-24 12:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_jobs', '0011_alter_job_days_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
        migrations.AlterField(
            model_name='job',
            name='days_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_requirements',
            field=ckeditor.fields.RichTextField(blank=True, default='Enter preferred requirements.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, to='djob_jobs.Tags'),
        ),
    ]
