# Generated by Django 3.2 on 2021-04-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
            ],
        ),
    ]
