# Generated by Django 3.2 on 2021-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_data', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='category',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
