# Generated by Django 3.1.7 on 2021-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_profile', '0003_profile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.TextField(blank=True, default='Analyze the needs of the user \nDesign, test and develop the software to meet those needs \nRecommend upgrades for existing systems and programs \nDevelop separate elements of a software that work well in the program as a whole\nCreate various diagrams, flowcharts and models that illustrate the type of code needed for programmers\nEnsure continued functionality of a program during maintenance and testing of software\nDocument each aspect of a system or application as a reference for future upgrades and maintenanceRevisit the development process to fix bugs or address client or consumer concerns\n', null=True),
        ),
    ]
