# Generated by Django 3.2.3 on 2021-05-28 23:33

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djob_profile', '0005_auto_20210328_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
