# Generated by Django 3.2.8 on 2021-10-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djob_profile', '0006_alter_experience_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.TextField(default='Default - I am an engineer'),
        ),
    ]
